<?php declare(strict_types=1);

$aSubs = [
'*5G Report',
'*5G Report #2',
'*5G video**',   
'*5G video #2***',
'*AIDS',    
'Alt\' Protocols»',
'Alt\' Therapies»',
'*Aquaponics',
'Autism',
'*Body\'s Manual ',
'*Brain Death***',
'Cancer',  
'*Cell Phones',
'*Cell Phones 2',
'Chemotherapy',
'Children',     
'*2010 report**',
'*Above report',
'*5G/COVID19**',
'*Agenda-COVID19',
'*All SCRIPTED',
'*Bill Gates',
'*BioTerror***',
'*Chloroquine',
'*CV19 or War?',
'*Dr. Bukacek***',
'*Dr. Buttar***',
'*DC Dr-HCQ wrks',
'*D.Icke-CV19',
'*D.Icke-CV19 2',
'*Dr. Horowitz**',
'*Dr S on CV19',
'*Drug Pulled!',
'*Event 201',
'*False Pandemic',
'*HCQ Video***',
'*Hosp\' Murder',
'*JR Report**',
'*Krystal Tini**',
'*Lies exposed',
'*MSM CV Fraud',
'*No bodies',
'*No bodies 2',
'*Not so Trusted',
'*Plandemic***',
'*Professor Witt',
'*St Louis Dr**',
'*Swiss Study***',
'*Taiwan TV',
'*Using Dummies?',
'*Virus Info***',
'*Vit C works!',
'*Conclusion',
'CPS',          
'Death Industry',
'*Doctors',   
'Dr. Carley/VIDS',
'FDA/AMA/BMA',   
'Fluoride',    
'General Health',
'GMOs',      
'Immortality',
'*Intrav\' Vit C',
'Mammographies',
'MMS',    
'Music',    
'Plant Music',  
'SIDS',     
'*Vaccines',   
'Water',    
];

