<?php declare(strict_types=1);

$aSubs = [
'*12Presumptions',
'2nd Amendment',
'A4V',     
'America . .  »',
'Basis of Law',
'*Black\'s Law',
'*Bouvier\'s Law',
'Cit v Nat',
'Commerce',
'Contracts',
'Driving v...',
'Free speech',
'HRJ 192',
'Honor/Dishonor',
'Dealing with...',
'Get rid of:  »',
'G. Guidestones',
'Gr8 Deception',
'*Intervention...',
'Jurisdictionary',
'*Law of Nations',
'*Letter 2 POTUS',
'Maxims: Law ...',
'*Neg\' Averment',
'Removing them',
'The BAR',
'*The Dick Act',
'The \'Queen\' ',
'The Rats & ...',
'Trading...',
'The UCC',
'*US Notice',
'US Reports',
'Various cites',
'*Your BC',
];

