<?php declare(strict_types=1);

$aSubs = [
'*7/7 (London bombing)',
'*911 (September Clues)',
'*The Climate Change scam',
'*Credo Mutwa',
'*David Brock - Media Matters Manifesto',
'*Elvis lives',
'False Flags',
'*Family Guardian',
'*Fukishima',
'*The George Floyd Psyop',
'*Jews/Neanderthals',
'*Jerry Kirk',
'*JFK Jr. & Snr.',
'Muamar Quadaffi',
'*Out of Shadows - the Movie',
'Princess Diana',
'Remote Viewing',
'Smart Meters',
'*Superbowl 51',
'*Scientology',
'*Silent Weapons for Quiet Wars',
'Telepathy',
'The Hitler files',
'The Jewish \'Problem\'',
'*The \'Over-population\' myth',
'The Scarcity Myth',
'*UK\'s \'Hidden Shadows\' - the UK version of \'Out of Shadows\' above',
'*Vatican Assassins',
'Your Future',
];

